apiVersion: v1
kind: Secret
metadata:
  name: just-for-chill-secret
  namespace: just-for-chill
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "your-secret-key-here"
  POSTGRES_USER: "behruz"
  POSTGRES_PASSWORD: "20090912"
