apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  namespace: just-for-chill
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: localhost:5000/django-app:latest
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
